# Generated by Django 5.0 on 2023-12-10 15:06
import requests
from django.db import migrations


def add_author_and_books(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Author = apps.get_model('books', 'Author')
    url = 'https://mybook.ru/api/books/?type=text&is_synced=true&o=popular&limit=200'
    response = requests.get(url)
    response.raise_for_status()
    for book in response.json()['objects']:
        book_code = book['id']
        author_first_name = book['main_author']['first_name']
        author_last_name = book['main_author']['last_name']
        title = book['name']
        author, create = Author.objects.get_or_create(first_name=author_first_name, last_name=author_last_name)
        Book.objects.update_or_create(code=book_code, title=title, author=author)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book'),
    ]

    operations = [
        migrations.RunPython(add_author_and_books),
    ]
