# Generated by Django 5.0 on 2023-12-19 16:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20231210_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_at', models.DateTimeField(default=datetime.datetime(2023, 12, 19, 16, 22, 2, 521745, tzinfo=datetime.timezone.utc), verbose_name='Дата взятия книги')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='books.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='books.reader', verbose_name='Читатель')),
            ],
        ),
    ]
