# Generated by Django 3.2.22 on 2023-12-30 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_reader_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='taking_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 19, 20, 2, 226114, tzinfo=utc), verbose_name='Дата взятия книги'),
        ),
    ]
