# Generated by Django 3.2.22 on 2024-01-02 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0006_alter_booking_taking_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.accounts', verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='taking_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 12, 57, 27, 722986, tzinfo=utc), verbose_name='Дата взятия книги'),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
