# Generated by Django 3.2.22 on 2024-01-03 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20240102_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='taking_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 19, 31, 44, 599866, tzinfo=utc), verbose_name='Дата взятия книги'),
        ),
    ]
