# Generated by Django 3.2.22 on 2024-01-09 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20240104_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='taking_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 20, 58, 7, 318701, tzinfo=utc), verbose_name='Дата взятия книги'),
        ),
    ]
