# Generated by Django 3.2.22 on 2024-01-17 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20240109_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='taking_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 16, 38, 14, 208994, tzinfo=utc), verbose_name='Дата взятия книги'),
        ),
    ]
