# Generated by Django 3.2.22 on 2024-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=200, null=True, verbose_name='Никнейм'),
        ),
    ]
