# Generated by Django 3.2.22 on 2024-01-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_account'),
        ('books', '0009_auto_20240104_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
